language: cpp
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev

  #build gtest
  - cd /usr/src/gtest
  - sudo env "PATH=$PATH" cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
