language: cpp
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev
script:
  - bash build_gtest.sh

  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
